### ISSUE TITLE
Startup not working with recent script updates

### ISSUE THREAD

**Issue by DannyDorito** [DannyDorito/DayZ-Startup-and-Restart-Script#9]
Reported: https://www.youtube.com/watch?v=VUmZvvDgypI

Users report that setting the exe path and server profile results in the script not starting.

**Comment by ironeyex** [comment]
Hey Danny, The batch file works before editing. But when I put in the path for server exe the script will flash the cmb box and close all in a second.
![2021-02-19 14_39_56-Jev - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/58816749/108511597-6c3a9d00-72c0-11eb-95ee-4c92fb6410ba.png)

**Comment by DannyDorito** [comment]
Hi, if you place another `\` at the end of the file path, to make it `C:\Program Files (x86)\Steam\steamapps\common\DayZServer\` and try running it again does that fix it?

**Comment by ironeyex** [comment]
Unfortunately not

**Comment by DannyDorito** [comment]
So I have updated the code, and will push this into a release.
Please download the latest version and let me know how it goes!

**Comment by DannyDorito** [comment]
Update to RC1.1 minimum,
https://github.com/DannyDorito/DayZ-Startup-and-Restart-Script/releases/tag/RC1.1

Closed
